# Generated by Django 5.1.5 on 2025-12-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_authorized',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pending_transfer',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
