# Generated by Django 5.1.5 on 2025-12-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile_is_authorized_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='transfer_pin',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
